### ISSUE TITLE
Mejorar data-binding

### ISSUE THREAD

**Issue by hvarg** [BarbaraUribe/INF322#1]
Para los tres componentes que crearon el están utilizando la propiedad `cursos`
Si bien esto es adecuado para `horario-clases` este comportamiento hace que sea más difícil generalizar `tabla-guion`.

Sería mejor utilizar más (o distintas) propiedades para `tabla-guion` de manera de individualizar mejor el horario de clases.

Queda a su discreción los objetos que quieran utilizar para lograr este comportamiento, por ejemplo, pueden modificar `cursos` para individualizar el horario de cada paralelo y luego enviar ese nuevo objeto al componente. 
```html
<tabla-guion .paralelo="${this._cursos[i].paralelo[j]}">
```
También podrían enviarle llaves al componente para poder buscar dentro de cursos
```html
<tabla-guion .cursos="${this._cursos}" .curso="algun_curso" .paralelo="algun_paralelo">
```

**Comment by Blarep** [comment]
Resuelto
